name: Deploy mdBook to GitHub Pages
on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install mdBook
        run: |
          mkdir bin
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.45/mdbook-v0.4.45-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
          echo "$(pwd)/bin" >> "${GITHUB_PATH}"
      - name: Install mdbook-trpl plugin
        run: |
          cargo install --locked --path packages/mdbook-trpl
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
      - name: Build book
        run: mdbook build
      - name: Copy Google verification file to book root
        run: cp googled521aa6affb4ec4e.html book/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
